### ISSUE TITLE
Agenda is mokerlelijk

### ISSUE THREAD

**Issue by neutron-cracker** [ichthus-utrecht/vue-JS-website#31]
Kijken of de oude agenda layout gebruikt kan worden

**Comment by neutron-cracker** [comment]
<img width="611" alt="image" src="https://github.com/ichthus-utrecht/vue-JS-website/assets/52654095/f0b649c2-15c2-4179-b9a7-738adbb7d318">
Deze kleuren komen niet overeen met de huisstijl

**Comment by 607GitHub** [comment]
De agenda is niet mokerlelijk meer, door een update van Googles kant. De kleuren hebben we denk ik geen invloed op.
Verder werkt deze agenda prima, en het bleek ingewikkeld om de oude agenda client-side te implementeren. Daarom sluit ik deze issue voorlopig.
