### ISSUE TITLE
Agenda van Churchbook gebruiken

### ISSUE THREAD

**Issue by 607GitHub** [ichthus-utrecht/vue-JS-website#36]
Als het goed is kan de agenda die in Churchbook gebruikt worden gebruikt worden op de nieuwe website, in plaats van dat de oude Google agenda gebruikt wordt.

**Comment by neutron-cracker** [comment]
Het lijkt erop dat we vanuit Churchbook niet de goede link kunnen gebruiken. Misschien kan de ab actis wel de goede link uit churchbook krijgen, dus daar moeten we even op wachten

**Comment by neutron-cracker** [comment]
Hierbij een linkje van Churchbook met een kleine uitleg hoe dat zou moeten: https://churchbook.notion.site/Agenda-op-kerkwebsite-tonen-ba7f6643876a4f7ab0932b8d29f19457
Dit is de link voor google calender gebruikers: https://ichthusutrecht.churchbook.nl/public/ical_all.cfm?kerk_id=1

**Comment by neutron-cracker** [comment]
Als we toch bezig zijn, kunnen we net zo goed iets als (FullCalendar)[https://fullcalendar.io/docs/vue] gebruiken
