### ISSUE TITLE
Icoontjes Facebook, Instagram, slotje

### ISSUE THREAD

**Issue by 607GitHub** [ichthus-utrecht/vue-JS-website#7]
Kan iemand aan de icoontjes voor Facebook, Instagram en het slotje bij 'Leden' komen, of aan alternatieven daarvoor?

**Comment by Rogue-Juan** [comment]
Slot icoontje komt hier vandaan: https://fontawesome.com/icons/lock?f=classic&s=solid. Weet alleen niet hoe je die toevoegt. Kan hem downloaden als .svg.

**Comment by 607GitHub** [comment]
Deze is op een gegeven moment gefikst door packages over te nemen van de oude website.
